.PHONY: all clean

# all:
# 	@mkdir test
# 	@cd test
# 	@mkdir subtest

# ------结果------
# 在当前目录下生成两个子目录test/，subtest/

all:
	@mkdir test;\
	cd test;\
	mkdir subtest

# ------结果------
# 在当前目录下生成子目录test/subtest/

clean:
	rm -rf test/ subtest/
