.PHONY: all

GCC = gcc
# GCCFLAGS = -lm -O3 -g # DEBUG
GCCFLAGS =
# all: epoll_demo.c
# 	$(GCC) $(GCCFLAGS) -o epolldemo epoll_demo.c

all: epoll_demo4.c
	$(GCC) $(GCCFLAGS) -o demo4 epoll_demo4.c

clean:
	rm -rf *.o
	rm -rf epolldemo